services:
  frontend:
    build: .
    container_name: nexus_leads
    ports:
      - "3006:8085"
    environment:
      - VITE_API_URL=https://apihomol.nexusvitally.com.br
    networks:
      - nexusnet

networks:
  nexusnet:
    external: true
